//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode2022 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Inputs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Inputs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode2022.Inputs", typeof(Inputs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18313
        ///2404
        ///10479
        ///
        ///7011
        ///10279
        ///1496
        ///10342
        ///8918
        ///3162
        ///4525
        ///4368
        ///
        ///17242
        ///
        ///10920
        ///14072
        ///9754
        ///4435
        ///9396
        ///
        ///5915
        ///2602
        ///4032
        ///3303
        ///2685
        ///1856
        ///1334
        ///4865
        ///6385
        ///1733
        ///5328
        ///
        ///8899
        ///5482
        ///3195
        ///7837
        ///8986
        ///13794
        ///
        ///25121
        ///22211
        ///21257
        ///
        ///6360
        ///4007
        ///5124
        ///2266
        ///6943
        ///6966
        ///3887
        ///3427
        ///1255
        ///5266
        ///6119
        ///2841
        ///
        ///6167
        ///3883
        ///2776
        ///5894
        ///2013
        ///6930
        ///6613
        ///4637
        ///5259
        ///2347
        ///3550
        ///5639
        ///5117
        ///
        ///4530
        ///5961
        ///5956
        ///2503
        ///5060
        ///4770
        ///5240
        ///4123
        ///4089
        ///6794
        ///3333
        ///5244
        ///4415
        ///
        ///1733
        ///1209
        ///4458
        ///1223
        ///3859
        ///7 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day1 {
            get {
                return ResourceManager.GetString("Day1", resourceCulture);
            }
        }
    }
}
