//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode2022 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Inputs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Inputs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode2022.Inputs", typeof(Inputs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18313
        ///2404
        ///10479
        ///
        ///7011
        ///10279
        ///1496
        ///10342
        ///8918
        ///3162
        ///4525
        ///4368
        ///
        ///17242
        ///
        ///10920
        ///14072
        ///9754
        ///4435
        ///9396
        ///
        ///5915
        ///2602
        ///4032
        ///3303
        ///2685
        ///1856
        ///1334
        ///4865
        ///6385
        ///1733
        ///5328
        ///
        ///8899
        ///5482
        ///3195
        ///7837
        ///8986
        ///13794
        ///
        ///25121
        ///22211
        ///21257
        ///
        ///6360
        ///4007
        ///5124
        ///2266
        ///6943
        ///6966
        ///3887
        ///3427
        ///1255
        ///5266
        ///6119
        ///2841
        ///
        ///6167
        ///3883
        ///2776
        ///5894
        ///2013
        ///6930
        ///6613
        ///4637
        ///5259
        ///2347
        ///3550
        ///5639
        ///5117
        ///
        ///4530
        ///5961
        ///5956
        ///2503
        ///5060
        ///4770
        ///5240
        ///4123
        ///4089
        ///6794
        ///3333
        ///5244
        ///4415
        ///
        ///1733
        ///1209
        ///4458
        ///1223
        ///3859
        ///7 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day1 {
            get {
                return ResourceManager.GetString("Day1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B Z
        ///B Z
        ///C Z
        ///C Z
        ///B X
        ///C Y
        ///A Y
        ///B Z
        ///A Z
        ///A Y
        ///C Z
        ///C X
        ///C Z
        ///C X
        ///B X
        ///B Z
        ///B Z
        ///A Z
        ///C Z
        ///C Z
        ///C Y
        ///C Z
        ///B Z
        ///B Z
        ///A X
        ///A Y
        ///B Z
        ///B Z
        ///C Z
        ///B Z
        ///B Z
        ///C X
        ///C Z
        ///A Y
        ///A X
        ///A X
        ///C Z
        ///C Z
        ///B X
        ///C X
        ///B Z
        ///A Z
        ///B X
        ///B Z
        ///B Z
        ///A Z
        ///B Z
        ///A Y
        ///C Z
        ///C Z
        ///B X
        ///C Z
        ///A Z
        ///C Z
        ///C Z
        ///C Z
        ///C Z
        ///A Z
        ///B Z
        ///C Z
        ///A Z
        ///C Z
        ///C Z
        ///C Y
        ///A Y
        ///C X
        ///C Z
        ///C Z
        ///C Z
        ///C Z
        ///A Y
        ///C X
        ///A Y
        ///A Y
        ///C X
        ///B Z
        ///A Y
        ///C Y
        ///C Z
        ///B Z
        ///C Z
        ///B Z
        ///B Z
        ///B Z
        ///C Y
        ///B Z
        ///A Y
        ///C Z
        ///C Z
        ///A X
        ///C X
        ///C Z
        ///A X
        ///C Z
        ///C Z
        ///C X
        ///A Z
        ///C Z
        ///C Z
        ///B Z
        ///C Y
        ///A Y
        ///C  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day2 {
            get {
                return ResourceManager.GetString("Day2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPstqDdrsqdDtqrFDJDDrmtsJHflSJCLgCphgHHgRHJCRRff
        ///BcBGcQzVBVZcvznTTTvZcGTpCRRRfRCggLflHlhhCZpZCj
        ///vGQnQvnzTzNTTbVnzGBqMqwqDLdPtMmbwqqLLM
        ///wLRFRqvFsFRjfrHddbdbjzdH
        ///lcsnSJPSSVVlGmGrHzbbrGNrdzbz
        ///mSmlnnPlmJmncVDSlSZSlmLBCvtwBvtLCqqswsDBCTWW
        ///pfqPrPgmmhvqdlsdWq
        ///nfjHLJfZcLbVtQWWtndhls
        ///CzJJFLzRzfDwrmggpC
        ///CWfllmlCDFlZZqMfmFBWmWLJVRLVwNNtRVGPpwtGpqbJ
        ///jHndndndcjhscnhHNtRbVtLbGpJbRRcb
        ///HSrvnQzQSMDlLzBCfg
        ///BQRVbgQQBJBbBtVBSSSRWMQbdNvvRPjZjCCdPLNZNNsNCCzd
        ///HwpFpnlGpGZWGvjzPd
        ///FTDmFrrwDpFMtmQVQQcWgc
        ///VhbPshVDPDFWhW [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day3 {
            get {
                return ResourceManager.GetString("Day3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 91-93,6-92
        ///85-97,18-63
        ///15-99,16-98
        ///35-49,34-50
        ///4-7,6-93
        ///57-86,57-58
        ///1-82,83-90
        ///21-88,20-89
        ///83-84,1-83
        ///8-82,7-83
        ///69-70,45-69
        ///18-92,93-95
        ///5-79,4-79
        ///10-15,11-90
        ///69-69,69-82
        ///67-67,67-86
        ///18-88,17-94
        ///42-60,43-89
        ///1-57,18-56
        ///32-34,32-35
        ///23-56,24-55
        ///68-68,67-67
        ///10-98,11-48
        ///12-57,13-29
        ///14-67,13-40
        ///35-37,36-84
        ///6-83,6-82
        ///29-50,28-29
        ///55-83,88-95
        ///43-96,43-66
        ///59-72,59-63
        ///52-69,70-83
        ///51-51,24-51
        ///91-99,91-98
        ///27-27,26-54
        ///36-42,36-42
        ///63-64,64-79
        ///24-68,23-24
        ///71-93,13-92
        ///57-82,56-56
        ///69-97 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day4 {
            get {
                return ResourceManager.GetString("Day4", resourceCulture);
            }
        }
    }
}
